# -*- coding: utf-8 -*-
# @Author: pengyi
# @Time  : 20/05/14


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,math
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

import configparser

from src import execute 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("产测")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menucaidan = QtWidgets.QMenu(self.menubar)
        self.menucaidan.setObjectName("menucaidan")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.nchpproduce = QtWidgets.QAction(MainWindow)
        self.nchpproduce.setObjectName("nchpproduce")
        self.oldproduce = QtWidgets.QAction(MainWindow)
        self.oldproduce.setObjectName("oldproduce")
        self.wholeproduce = QtWidgets.QAction(MainWindow)
        self.wholeproduce.setObjectName("wholeproduce")
        self.actionmx2080 = QtWidgets.QAction(MainWindow)
        self.actionmx2080.setObjectName("actionmx2080")
        self.dpow = QtWidgets.QAction(MainWindow)
        self.dpow.setObjectName("dpow")
        self.loadfile = QtWidgets.QAction(MainWindow)
        self.loadfile.setObjectName("loadfile")
        self.menu.addAction(self.loadfile)
        self.menucaidan.addAction(self.nchpproduce)
        self.menucaidan.addAction(self.nchpproduce)
        self.menucaidan.addAction(self.oldproduce)
        self.menucaidan.addAction(self.wholeproduce)
        self.menucaidan.addAction(self.actionmx2080)
        self.menucaidan.addAction(self.dpow)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menucaidan.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.__mainwindow = MainWindow
        MainWindow.setWindowTitle(_translate("MainWindow",  "产测助手"))
        self.menu.setTitle(_translate("MainWindow",  "文件"))
        self.menucaidan.setTitle(_translate("MainWindow",  "生产类型"))
        self.loadfile.setText(_translate("MainWindow",  "一键导入"))
        self.nchpproduce.setText(_translate("MainWindow",  "信道板产测"))
        self.oldproduce.setText(_translate("MainWindow",  "信道板老化"))
        self.wholeproduce.setText(_translate("MainWindow",  "整机产测"))
        self.actionmx2080.setText(_translate("MainWindow",  "mx2080整机产测"))
        self.dpow.setText(_translate("MainWindow",  "整机功率校准"))
        
        self.loadfile.triggered.connect(self.oneloadfile)
        self.nchpproduce.triggered.connect(self.shownchpproduce)
        self.oldproduce.triggered.connect(self.showoldproduce)
        self.wholeproduce.triggered.connect(self.showwholeproduce)
        self.actionmx2080.triggered.connect(self.showmx2080)
        self.dpow.triggered.connect(self.showdpow)
        self.shownchpproduce()

    def oneloadfile(self):
        dialog = QFileDialog()
        dialog.setFileMode(QFileDialog.AnyFile)
        dialog.setFilter(QDir.Files)

        if dialog.exec():
            filenames = dialog.selectedFiles()
            self.__cfg = configparser.ConfigParser()
            
            self.__cfg.read(filenames[0], encoding='UTF-8')
            yield_type = self.__cfg.sections()
            if yield_type[0] != "yield_type":
                QMessageBox.about(self.__mainwindow, "错误", "缺少生产类型")
                return
            else:
                num = int(self.__cfg.get("yield_type","type"))
            #信道板产测
            if num == 0:
                self.shownchpproduce()
                '''
                #self.plat_name_comboBox.setCurrentText(self.cfg.get("plat","plat_name"))
                self.local_ip_lineEdit.setText(self.cfg.get("dut","local_ip"))
                self.dev_ip_lineEdit.setText(self.cfg.get("dut", "dev_ip"))
                self.sa_ip_lineEdit.setText(self.cfg.get("dut","sa_ip"))
                #self.double_nchp_checkBox.styleSheet(cfg.get("dut","nchp_num"))
                self.nchp_ip_lineEdit.setText(self.cfg.get("dut","nchp_ip"))
                self.mssh_port_lineEdit.setText(self.cfg.get("dut","ssh_port"))
                self.mssh_user_lineEdit.setText(self.cfg.get("dut","username"))
                self.mssh_password_lineEdit.setText(self.cfg.get("dut","password"))
                self.mssh_password_lineEdit_2.setText(self.cfg.get("dut","password2"))
                self.nssh_port_lineEdit.setText(self.cfg.get("nchp","ssh_port"))
                self.nssh_user_lineEdit.setText(self.cfg.get("nchp","username"))
                self.nssh_password_lineEdit.setText(self.cfg.get("nchp","password"))
                '''
            #信道板老化
            elif num == 1:
                self.showoldproduce()
            #整机产测
            elif num == 2:
                self.showwholeproduce()
            #MX2080整机产测
            elif num == 3:
                self.showmx2080()
            #整机功率校准
            elif num == 4:
                self.showdpow()
                #界面填写
                self.local_ip_lineEdit.setText(self.__cfg.get("dut","local_ip"))
                self.dev_ip_lineEdit.setText(self.__cfg.get("dut", "dev_ip"))
                self.sa_ip_lineEdit.setText(self.__cfg.get("dut","sa_ip"))
                self.mssh_port_lineEdit.setText(self.__cfg.get("dut","ssh_port"))
                self.mssh_user_lineEdit.setText(self.__cfg.get("dut","username"))
                self.mssh_password_lineEdit.setText(self.__cfg.get("dut","password"))
                self.mssh_password_lineEdit_2.setText(self.__cfg.get("dut","password2"))
                self.external_gain_lineEdit.setText(self.__cfg.get("common","external_gain"))
            else:
                QMessageBox.about(self.__mainwindow, "错误", "生产类型错误")
                return
    def shownchpproduce(self):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 70, 301, 351))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.plat_name_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.plat_name_lable.setObjectName("plat_name_lable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.plat_name_lable)
        self.plat_name_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.plat_name_comboBox.setObjectName("plat_name_comboBox")
        self.plat_name_comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plat_name_comboBox)
        self.local_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.local_ip_lable.setObjectName("local_ip_lable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.local_ip_lable)
        self.local_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.local_ip_lineEdit.setObjectName("local_ip_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.local_ip_lineEdit)
        self.dev_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_ip_lable.setObjectName("dev_ip_lable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dev_ip_lable)
        self.dev_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_ip_lineEdit.setObjectName("dev_ip_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dev_ip_lineEdit)
        self.sa_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.sa_ip_lable.setObjectName("sa_ip_lable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sa_ip_lable)
        self.sa_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sa_ip_lineEdit.setObjectName("sa_ip_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sa_ip_lineEdit)
        self.mssh_port_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_port_lable.setObjectName("mssh_port_lable")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mssh_port_lable)
        self.mssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_port_lineEdit.setObjectName("mssh_port_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mssh_port_lineEdit)
        self.mssh_user_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_user_lable.setObjectName("mssh_user_lable")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mssh_user_lable)
        self.mssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_user_lineEdit.setObjectName("mssh_user_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mssh_user_lineEdit)
        self.mssh_password_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_lable.setObjectName("mssh_password_lable")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mssh_password_lable)
        self.mssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit.setObjectName("mssh_password_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit)
        self.mssh_password_lable_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_lable_2.setObjectName("mssh_password_lable_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.mssh_password_lable_2)
        self.mssh_password_lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit_2.setObjectName("mssh_password_lineEdit_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit_2)
        self.upper_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.upper_limit_lable.setObjectName("upper_limit_lable")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.upper_limit_lable)
        self.upper_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.upper_limit_spinBox.setMinimum(1)
        self.upper_limit_spinBox.setMaximum(100)
        self.upper_limit_spinBox.setObjectName("upper_limit_spinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.upper_limit_spinBox)
        self.lower_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.lower_limit_lable.setObjectName("lower_limit_lable")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lower_limit_lable)
        self.lower_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.lower_limit_spinBox.setObjectName("lower_limit_spinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lower_limit_spinBox)
        self.log_level_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.log_level_lable.setObjectName("log_level_lable")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.log_level_lable)
        self.log_level_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.log_level_spinBox.setMaximum(7)
        self.log_level_spinBox.setObjectName("log_level_spinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.log_level_spinBox)
        self.save_log_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.save_log_checkBox.setObjectName("save_log_checkBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.save_log_checkBox)
        self.nchpproduce_lable = QtWidgets.QLabel(self.centralwidget)
        self.nchpproduce_lable.setGeometry(QtCore.QRect(280, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nchpproduce_lable.setFont(font)
        self.nchpproduce_lable.setObjectName("nchpproduce_lable")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(379, 70, 301, 374))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nchp_num_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.nchp_num_checkBox.setObjectName("nchp_num_checkBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nchp_num_checkBox)
        self.nchp_ip_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_ip_lable.setObjectName("nchp_ip_lable")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nchp_ip_lable)
        self.nchp_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nchp_ip_lineEdit.setObjectName("nchp_ip_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nchp_ip_lineEdit)
        self.nssh_port_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nssh_port_lable.setObjectName("nssh_port_lable")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nssh_port_lable)
        self.nssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nssh_port_lineEdit.setObjectName("nssh_port_lineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nssh_port_lineEdit)
        self.nssh_user = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nssh_user.setObjectName("nssh_user")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nssh_user)
        self.nssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nssh_user_lineEdit.setObjectName("nssh_user_lineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nssh_user_lineEdit)
        self.nssh_password_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nssh_password_lable.setObjectName("nssh_password_lable")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.nssh_password_lable)
        self.nssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nssh_password_lineEdit.setObjectName("nssh_password_lineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nssh_password_lineEdit)
        self.band_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.band_lable.setObjectName("band_lable")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.band_lable)
        self.band_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.band_lineEdit.setObjectName("band_lineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.band_lineEdit)
        self.nchp_arfc_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_arfc_lable.setObjectName("nchp_arfc_lable")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.nchp_arfc_lable)
        self.nchp_arfc_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nchp_arfc_lineEdit.setObjectName("nchp_arfc_lineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.nchp_arfc_lineEdit)
        self.nchp_freq_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_freq_lable.setObjectName("nchp_freq_lable")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.nchp_freq_lable)
        self.nchp_freq_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nchp_freq_lineEdit.setObjectName("nchp_freq_lineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.nchp_freq_lineEdit)
        self.nchp_gain_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_gain_lable.setObjectName("nchp_gain_lable")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.nchp_gain_lable)
        self.nchp_gain_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nchp_gain_lineEdit.setObjectName("nchp_gain_lineEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.nchp_gain_lineEdit)
        self.power_level_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.power_level_lable.setObjectName("power_level_lable")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.power_level_lable)
        self.power_level_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.power_level_spinBox.setMaximum(20)
        self.power_level_spinBox.setObjectName("power_level_spinBox")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.power_level_spinBox)
        self.acp_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.acp_lable.setObjectName("acp_lable")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.acp_lable)
        self.acpl_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.acpl_lineEdit.setObjectName("acpl_lineEdit")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.acpl_lineEdit)
        self.reset_pin_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.reset_pin_lable.setObjectName("reset_pin_lable")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.reset_pin_lable)
        self.reset_pin_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.reset_pin_lineEdit.setObjectName("reset_pin_lineEdit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.reset_pin_lineEdit)
        self.ant_num_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.ant_num_lable.setObjectName("ant_num_lable")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.ant_num_lable)
        self.ant_num_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.ant_num_spinBox.setMaximum(10)
        self.ant_num_spinBox.setObjectName("ant_num_spinBox")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.ant_num_spinBox)
        self.boot_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.boot_version_label.setObjectName("boot_version_label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.boot_version_label)
        self.boot_version_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.boot_version_lineEdit.setObjectName("boot_version_lineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.boot_version_lineEdit)
        self.nchp_produce_start = QtWidgets.QPushButton(self.centralwidget)
        self.nchp_produce_start.setGeometry(QtCore.QRect(550, 460, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nchp_produce_start.setFont(font)
        self.nchp_produce_start.setObjectName("nchp_produce_start")
        MainWindow.setCentralWidget(self.centralwidget)

        self.plat_name_lable.setText("plat")
        self.plat_name_comboBox.setItemText(0, "ta332_71")
        self.local_ip_lable.setText("本机IP")
        self.dev_ip_lable.setText("主控IP")
        self.sa_ip_lable.setText("仪表IP")
        self.mssh_port_lable.setText("主控ssh端口")
        self.mssh_user_lable.setText("主控登陆用户")
        self.mssh_password_lable.setText("主控一级密码")
        self.mssh_password_lable_2.setText("主控二级密码")
        self.upper_limit_lable.setText("温度上限")
        self.lower_limit_lable.setText("温度下限")
        self.log_level_lable.setText("log等级")
        self.save_log_checkBox.setText("保存文件log")
        self.nchpproduce_lable.setText("信道板产测")
        self.nchp_num_checkBox.setText("是否为双信道板")
        self.nchp_ip_lable.setText("信道板IP")
        self.nssh_port_lable.setText("信道板ssh端口")
        self.nssh_user.setText("信道板ssh登陆用户")
        self.nssh_password_lable.setText("信道板ssh登陆密码")
        self.band_lable.setText("band")
        self.nchp_arfc_lable.setText("频点")
        self.nchp_freq_lable.setText("频率")
        self.nchp_gain_lable.setText("接收功率")
        self.power_level_lable.setText("功率等级")
        self.acp_lable.setText("acpl")
        self.reset_pin_lable.setText("信道板复位引脚")
        self.ant_num_lable.setText("天线个数")
        self.boot_version_label.setText("boot版本")
        self.nchp_produce_start.setText("start")

        #信道板老化
    def showoldproduce(self):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.oldproduce_lable = QtWidgets.QLabel(self.centralwidget)
        self.oldproduce_lable.setGeometry(QtCore.QRect(290, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.oldproduce_lable.setFont(font)
        self.oldproduce_lable.setObjectName("oldproduce_lable")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(140, 80, 381, 351))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dev_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_ip_lable.setObjectName("dev_ip_lable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dev_ip_lable)
        self.dut_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dut_ip_lineEdit.setObjectName("dut_ip_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dut_ip_lineEdit)
        self.mssh_port_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_port_lable.setObjectName("mssh_port_lable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mssh_port_lable)
        self.mssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_port_lineEdit.setObjectName("mssh_port_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mssh_port_lineEdit)
        self.mssh_user_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_user_lable.setObjectName("mssh_user_lable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mssh_user_lable)
        self.mssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_user_lineEdit.setObjectName("mssh_user_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mssh_user_lineEdit)
        self.mssh_password_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_lable.setObjectName("mssh_password_lable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mssh_password_lable)
        self.mssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit.setObjectName("mssh_password_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit)
        self.mssh_password_lable_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_lable_2.setObjectName("mssh_password_lable_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mssh_password_lable_2)
        self.mssh_password_lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit_2.setObjectName("mssh_password_lineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit_2)
        self.nssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nssh_user_lineEdit.setObjectName("nssh_user_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.nssh_user_lineEdit)
        self.nssh_user_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.nssh_user_lable.setObjectName("nssh_user_lable")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.nssh_user_lable)
        self.nssh_password_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.nssh_password_lable.setObjectName("nssh_password_lable")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nssh_password_lable)
        self.nssh_user_lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nssh_user_lineEdit_2.setObjectName("nssh_user_lineEdit_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nssh_user_lineEdit_2)
        self.led_pin_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.led_pin_lable.setObjectName("led_pin_lable")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.led_pin_lable)
        self.led_pin_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.led_pin_lineEdit.setObjectName("led_pin_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.led_pin_lineEdit)
        self.upper_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.upper_limit_lable.setObjectName("upper_limit_lable")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.upper_limit_lable)
        self.upper_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.upper_limit_spinBox.setMinimum(1)
        self.upper_limit_spinBox.setMaximum(100)
        self.upper_limit_spinBox.setObjectName("upper_limit_spinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.upper_limit_spinBox)
        self.lower_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.lower_limit_lable.setObjectName("lower_limit_lable")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lower_limit_lable)
        self.lower_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.lower_limit_spinBox.setObjectName("lower_limit_spinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lower_limit_spinBox)
        self.log_level_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.log_level_lable.setObjectName("log_level_lable")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.log_level_lable)
        self.log_level_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.log_level_spinBox.setMaximum(7)
        self.log_level_spinBox.setProperty("value", 7)
        self.log_level_spinBox.setObjectName("log_level_spinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.log_level_spinBox)
        self.save_log_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.save_log_checkBox.setObjectName("save_log_checkBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.save_log_checkBox)
        self.oldnchp_start = QtWidgets.QPushButton(self.centralwidget)
        self.oldnchp_start.setGeometry(QtCore.QRect(544, 450, 121, 23))
        self.oldnchp_start.setObjectName("oldnchp_start")
        MainWindow.setCentralWidget(self.centralwidget)

        self.oldproduce_lable.setText( "信道板老化")
        self.dev_ip_lable.setText( "主控IP")
        self.mssh_port_lable.setText( "主控ssh端口")
        self.mssh_user_lable.setText( "主控ssh用户")
        self.mssh_password_lable.setText( "主控ssh一级密码")
        self.mssh_password_lable_2.setText( "主控ssh二级密码")
        self.nssh_user_lable.setText( "信道板ssh用户")
        self.nssh_password_lable.setText( "信道板ssh密码")
        self.led_pin_lable.setText( "led灯引脚")
        self.upper_limit_lable.setText( "温度上限")
        self.lower_limit_lable.setText( "温度下限")
        self.log_level_lable.setText( "日志等级")
        self.save_log_checkBox.setText( "保存文件log")
        self.oldnchp_start.setText( "start")

        #整机产测
    def showwholeproduce(self):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wholeproduce = QtWidgets.QLabel(self.centralwidget)
        self.wholeproduce.setGeometry(QtCore.QRect(290, 10, 131, 16))
        self.wholeproduce.setObjectName("wholeproduce")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 70, 311, 411))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dev_type_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_type_lable.setObjectName("dev_type_lable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dev_type_lable)
        self.dev_type_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_type_lineEdit.setObjectName("dev_type_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dev_type_lineEdit)
        self.oem_company_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.oem_company_lable.setObjectName("oem_company_lable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.oem_company_lable)
        self.oem_company_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.oem_company_comboBox.setObjectName("oem_company_comboBox")
        self.oem_company_comboBox.addItem("")
        self.oem_company_comboBox.addItem("")
        self.oem_company_comboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.oem_company_comboBox)
        self.local_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.local_ip_lable.setObjectName("local_ip_lable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.local_ip_lable)
        self.local_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.local_ip_lineEdit.setObjectName("local_ip_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.local_ip_lineEdit)
        self.dev_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_ip_lable.setObjectName("dev_ip_lable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dev_ip_lable)
        self.dev_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_ip_lineEdit.setObjectName("dev_ip_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dev_ip_lineEdit)
        self.mssh_port_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_port_lable.setObjectName("mssh_port_lable")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mssh_port_lable)
        self.mssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_port_lineEdit.setObjectName("mssh_port_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mssh_port_lineEdit)
        self.mssh_password_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_lable.setObjectName("mssh_password_lable")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mssh_password_lable)
        self.mssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit.setObjectName("mssh_password_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit)
        self.mssh_password_lable_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_lable_2.setObjectName("mssh_password_lable_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mssh_password_lable_2)
        self.mssh_password_lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit_2.setObjectName("mssh_password_lineEdit_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit_2)
        self.mcb_version_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.mcb_version_lable.setObjectName("mcb_version_lable")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.mcb_version_lable)
        self.mcb_version_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mcb_version_lineEdit.setObjectName("mcb_version_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mcb_version_lineEdit)
        self.upper_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.upper_limit_lable.setObjectName("upper_limit_lable")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.upper_limit_lable)
        self.upper_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.upper_limit_spinBox.setMinimum(1)
        self.upper_limit_spinBox.setMaximum(100)
        self.upper_limit_spinBox.setObjectName("upper_limit_spinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.upper_limit_spinBox)
        self.lower_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.lower_limit_lable.setObjectName("lower_limit_lable")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lower_limit_lable)
        self.lower_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.lower_limit_spinBox.setObjectName("lower_limit_spinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lower_limit_spinBox)
        self.rssi_lower_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.rssi_lower_limit_lable.setObjectName("rssi_lower_limit_lable")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.rssi_lower_limit_lable)
        self.rssi_lower_limit_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rssi_lower_limit_lineEdit.setObjectName("rssi_lower_limit_lineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.rssi_lower_limit_lineEdit)
        self.rssi_upper_limit_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.rssi_upper_limit_lable.setObjectName("rssi_upper_limit_lable")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.rssi_upper_limit_lable)
        self.rssi_upper_limit_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rssi_upper_limit_lineEdit.setObjectName("rssi_upper_limit_lineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.rssi_upper_limit_lineEdit)
        self.power_warn_time_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.power_warn_time_lable.setObjectName("power_warn_time_lable")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.power_warn_time_lable)
        self.power_warn_time_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.power_warn_time_spinBox.setMaximum(100)
        self.power_warn_time_spinBox.setObjectName("power_warn_time_spinBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.power_warn_time_spinBox)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(380, 70, 291, 100))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nchp_gsm_version_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_gsm_version_lable.setObjectName("nchp_gsm_version_lable")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nchp_gsm_version_lable)
        self.nchp_gsm_version_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nchp_gsm_version_lineEdit.setObjectName("nchp_gsm_version_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nchp_gsm_version_lineEdit)
        self.nchp_lte_version_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_lte_version_lable.setObjectName("nchp_lte_version_lable")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nchp_lte_version_lable)
        self.nchp_lte_version_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nchp_lte_version_lineEdit.setObjectName("nchp_lte_version_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nchp_lte_version_lineEdit)
        self.count_lower_limit = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.count_lower_limit.setObjectName("count_lower_limit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.count_lower_limit)
        self.count_lower_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.count_lower_limit_spinBox.setObjectName("count_lower_limit_spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.count_lower_limit_spinBox)
        self.plat_name_lable = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.plat_name_lable.setObjectName("plat_name_lable")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.plat_name_lable)
        self.plat_name_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.plat_name_comboBox.setObjectName("plat_name_comboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plat_name_comboBox)
        self.whole_produce_start = QtWidgets.QPushButton(self.centralwidget)
        self.whole_produce_start.setGeometry(QtCore.QRect(540, 500, 75, 23))
        self.whole_produce_start.setObjectName("whole_produce_start")
        MainWindow.setCentralWidget(self.centralwidget)

        self.wholeproduce.setText("整机产测")
        self.dev_type_lable.setText("设备类型")
        self.oem_company_lable.setText("oem")
        self.oem_company_comboBox.setItemText(0, "fiberhome")
        self.oem_company_comboBox.setItemText(1, "other")
        self.oem_company_comboBox.setItemText(2, "unset")
        self.local_ip_lable.setText("本机IP")
        self.dev_ip_lable.setText("主控ip")
        self.mssh_port_lable.setText("主控ssh端口")
        self.mssh_password_lable.setText("主控ssh一级密码")
        self.mssh_password_lable_2.setText("主控ssh二级密码")
        self.mcb_version_lable.setText("主控版本")
        self.upper_limit_lable.setText("温度上限")
        self.lower_limit_lable.setText("温度下限")
        self.rssi_lower_limit_lable.setText("WiFi信号强度上限")
        self.rssi_upper_limit_lable.setText("WiFi信号强度下限")
        self.power_warn_time_lable.setText("掉电告警等待时间")
        self.nchp_gsm_version_lable.setText("gsm信道板版本")
        self.nchp_lte_version_lable.setText("lte信道板版本")
        self.count_lower_limit.setText("上号数量下限")
        self.plat_name_lable.setText("设备型号")
        self.whole_produce_start.setText("start")


        #MX2080整机产测
    def showmx2080(self):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MX2080 = QtWidgets.QLabel(self.centralwidget)
        self.MX2080.setGeometry(QtCore.QRect(310, 20, 141, 16))
        self.MX2080.setObjectName("MX2080")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 271, 412))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.plat_name_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.plat_name_lable.setObjectName("plat_name_lable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.plat_name_lable)
        self.plat_name_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.plat_name_comboBox.setObjectName("plat_name_comboBox")
        self.plat_name_comboBox.addItem("")
        self.plat_name_comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plat_name_comboBox)
        self.dev_type_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_type_label.setObjectName("dev_type_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dev_type_label)
        self.dev_type_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.dev_type_comboBox.setObjectName("dev_type_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dev_type_comboBox)
        self.oem_company_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.oem_company_lable.setObjectName("oem_company_lable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.oem_company_lable)
        self.oem_company_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.oem_company_comboBox.setObjectName("oem_company_comboBox")
        self.oem_company_comboBox.addItem("")
        self.oem_company_comboBox.addItem("")
        self.oem_company_comboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.oem_company_comboBox)
        self.local_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.local_ip_lable.setObjectName("local_ip_lable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.local_ip_lable)
        self.local_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.local_ip_lineEdit.setObjectName("local_ip_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.local_ip_lineEdit)
        self.dev_ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_ip_label.setObjectName("dev_ip_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.dev_ip_label)
        self.dev_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_ip_lineEdit.setObjectName("dev_ip_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dev_ip_lineEdit)
        self.mssh_port_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_port_label.setObjectName("mssh_port_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mssh_port_label)
        self.mssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_port_lineEdit.setObjectName("mssh_port_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mssh_port_lineEdit)
        self.mssh_user_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_user_label.setObjectName("mssh_user_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mssh_user_label)
        self.mssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_user_lineEdit.setObjectName("mssh_user_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mssh_user_lineEdit)
        self.mssh_password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label.setObjectName("mssh_password_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label)
        self.mssh_pass_word_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_pass_word_lineEdit.setObjectName("mssh_pass_word_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mssh_pass_word_lineEdit)
        self.mssh_password_label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label_2.setObjectName("mssh_password_label_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label_2)
        self.mssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit.setObjectName("mssh_password_lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit)
        self.mcb_version_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mcb_version_label.setObjectName("mcb_version_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.mcb_version_label)
        self.mcb_version_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mcb_version_lineEdit.setObjectName("mcb_version_lineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.mcb_version_lineEdit)
        self.upper_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.upper_limit_label.setObjectName("upper_limit_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.upper_limit_label)
        self.lower_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.lower_limit_label.setObjectName("lower_limit_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lower_limit_label)
        self.rssi_lower_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.rssi_lower_limit_label.setObjectName("rssi_lower_limit_label")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.rssi_lower_limit_label)
        self.rssi_lower_limit_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rssi_lower_limit_lineEdit.setObjectName("rssi_lower_limit_lineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.rssi_lower_limit_lineEdit)
        self.rssi_upper_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.rssi_upper_limit_label.setObjectName("rssi_upper_limit_label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.rssi_upper_limit_label)
        self.rssi_upper_limit_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rssi_upper_limit_lineEdit.setObjectName("rssi_upper_limit_lineEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.rssi_upper_limit_lineEdit)
        self.power_warn_time_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.power_warn_time_label.setObjectName("power_warn_time_label")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.power_warn_time_label)
        self.power_warn_time_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.power_warn_time_spinBox.setMaximum(3600)
        self.power_warn_time_spinBox.setObjectName("power_warn_time_spinBox")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.power_warn_time_spinBox)
        self.log_level_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.log_level_label.setObjectName("log_level_label")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.log_level_label)
        self.log_level_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.log_level_spinBox.setMaximum(7)
        self.log_level_spinBox.setObjectName("log_level_spinBox")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.log_level_spinBox)
        self.upper_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.upper_limit_spinBox.setMinimum(1)
        self.upper_limit_spinBox.setMaximum(100)
        self.upper_limit_spinBox.setObjectName("upper_limit_spinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.upper_limit_spinBox)
        self.lower_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.lower_limit_spinBox.setObjectName("lower_limit_spinBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lower_limit_spinBox)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(340, 70, 261, 318))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nchp_lte_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_lte_version_label.setObjectName("nchp_lte_version_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nchp_lte_version_label)
        self.nchp_lte_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.nchp_lte_version_comboBox.setObjectName("nchp_lte_version_comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nchp_lte_version_comboBox)
        self.nchp_gsm_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_gsm_version_label.setObjectName("nchp_gsm_version_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nchp_gsm_version_label)
        self.nchp_gsm_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.nchp_gsm_version_comboBox.setObjectName("nchp_gsm_version_comboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nchp_gsm_version_comboBox)
        self.count_lower_limit_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.count_lower_limit_label.setObjectName("count_lower_limit_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.count_lower_limit_label)
        self.count_lower_limitt_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.count_lower_limitt_spinBox.setObjectName("count_lower_limitt_spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.count_lower_limitt_spinBox)
        self.cpu_num_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.cpu_num_label.setObjectName("cpu_num_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cpu_num_label)
        self.cpu_num_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.cpu_num_spinBox.setMaximum(98)
        self.cpu_num_spinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.cpu_num_spinBox.setObjectName("cpu_num_spinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cpu_num_spinBox)
        self.led_pins_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.led_pins_label.setObjectName("led_pins_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.led_pins_label)
        self.led_pins_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.led_pins_lineEdit.setObjectName("led_pins_lineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.led_pins_lineEdit)
        self.rtc_in_cpu_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rtc_in_cpu_label.setObjectName("rtc_in_cpu_label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.rtc_in_cpu_label)
        self.rtc_in_cpu_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.rtc_in_cpu_spinBox.setObjectName("rtc_in_cpu_spinBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rtc_in_cpu_spinBox)
        self.wifi_in_cpu_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.wifi_in_cpu_label.setObjectName("wifi_in_cpu_label")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.wifi_in_cpu_label)
        self.wifi_in_cpu_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.wifi_in_cpu_spinBox.setObjectName("wifi_in_cpu_spinBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.wifi_in_cpu_spinBox)
        self.cell_mode_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.cell_mode_label.setObjectName("cell_mode_label")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.cell_mode_label)
        self.cell_mode_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.cell_mode_lineEdit.setObjectName("cell_mode_lineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cell_mode_lineEdit)
        self.TDD_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.TDD_version_label.setObjectName("TDD_version_label")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.TDD_version_label)
        self.TDD_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.TDD_version_comboBox.setObjectName("TDD_version_comboBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.TDD_version_comboBox)
        self.FDD_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.FDD_version_label.setObjectName("FDD_version_label")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.FDD_version_label)
        self.FDD_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.FDD_version_comboBox.setObjectName("FDD_version_comboBox")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.FDD_version_comboBox)
        self.GSM_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.GSM_version_label.setObjectName("GSM_version_label")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.GSM_version_label)
        self.GSM_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.GSM_version_comboBox.setObjectName("GSM_version_comboBox")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.GSM_version_comboBox)
        self.loadltever = QtWidgets.QPushButton(self.centralwidget)
        self.loadltever.setGeometry(QtCore.QRect(610, 70, 31, 23))
        self.loadltever.setObjectName("loadltever")
        self.loadgsmver = QtWidgets.QPushButton(self.centralwidget)
        self.loadgsmver.setGeometry(QtCore.QRect(610, 100, 31, 23))
        self.loadgsmver.setObjectName("loadgsmver")
        self.mx2080_start = QtWidgets.QPushButton(self.centralwidget)
        self.mx2080_start.setGeometry(QtCore.QRect(510, 480, 121, 23))
        self.mx2080_start.setObjectName("mx2080_start")
        MainWindow.setCentralWidget(self.centralwidget)

        self.MX2080.setText("MX2080整机产测")
        self.plat_name_lable.setText("设备型号")
        self.plat_name_comboBox.setItemText(0, "MX2080-G2L4")
        self.plat_name_comboBox.setItemText(1, "MX2080-L4")
        self.dev_type_label.setText("设备类型")
        self.oem_company_lable.setText("oem")
        self.oem_company_comboBox.setItemText(0, "fiberhome")
        self.oem_company_comboBox.setItemText(1, "other")
        self.oem_company_comboBox.setItemText(2, "unset")
        self.local_ip_lable.setText("本机IP")
        self.dev_ip_label.setText("主控IP")
        self.mssh_port_label.setText("主控ssh端口")
        self.mssh_user_label.setText("主控ssh用户")
        self.mssh_password_label.setText("主控ssh一级密码")
        self.mssh_password_label_2.setText("主控ssh二级密码")
        self.mcb_version_label.setText("主控版本")
        self.upper_limit_label.setText("温度上限")
        self.lower_limit_label.setText("温度下限")
        self.rssi_lower_limit_label.setText("WiFi信号强度上限")
        self.rssi_upper_limit_label.setText("WiFi信号强度下限")
        self.power_warn_time_label.setText("掉电告警等待时间")
        self.log_level_label.setText("日志打印级别")
        self.nchp_lte_version_label.setText("lte对应版本")
        self.nchp_gsm_version_label.setText("gsm对应版本")
        self.count_lower_limit_label.setText("上号数量下限")
        self.cpu_num_label.setText("cpu个数")
        self.led_pins_label.setText("led引脚")
        self.rtc_in_cpu_label.setText("rtc_in_cpu")
        self.wifi_in_cpu_label.setText("wifi_in_cpu")
        self.cell_mode_label.setText("cell_mode")
        self.TDD_version_label.setText("TDD版本")
        self.FDD_version_label.setText("FDD版本")
        self.GSM_version_label.setText("GSM版本")
        self.loadltever.setText("上传")
        self.loadgsmver.setText("上传")
        self.mx2080_start.setText("start")



        #整机功率校准
    def showdpow(self):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pdow = QtWidgets.QLabel(self.centralwidget)
        self.pdow.setGeometry(QtCore.QRect(280, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pdow.setFont(font)
        self.pdow.setObjectName("pdow")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 60, 241, 230))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.local_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.local_label.setObjectName("local_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.local_label)
        self.local_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.local_ip_lineEdit.setObjectName("local_ip_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.local_ip_lineEdit)
        self.dev_ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_ip_label.setObjectName("dev_ip_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dev_ip_label)
        self.dev_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_ip_lineEdit.setObjectName("dev_ip_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dev_ip_lineEdit)
        self.sa_ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.sa_ip_label.setObjectName("sa_ip_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sa_ip_label)
        self.sa_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sa_ip_lineEdit.setObjectName("sa_ip_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sa_ip_lineEdit)
        self.mssh_port_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_port_label.setObjectName("mssh_port_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mssh_port_label)
        self.mssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_port_lineEdit.setObjectName("mssh_port_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mssh_port_lineEdit)
        self.mssh_user_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_user_label.setObjectName("mssh_user_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mssh_user_label)
        self.mssh_password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label.setObjectName("mssh_password_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label)
        self.mssh_password_label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label_2.setObjectName("mssh_password_label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label_2)
        self.external_gain_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.external_gain_label.setObjectName("external_gain_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.external_gain_label)
        self.dev_mac_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_mac_lable.setObjectName("dev_mac_lable")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.dev_mac_lable)
        self.mssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_user_lineEdit.setObjectName("mssh_user_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mssh_user_lineEdit)
        self.mssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit.setObjectName("mssh_password_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit)
        self.mssh_password_lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit_2.setObjectName("mssh_password_lineEdit_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit_2)
        self.external_gain_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.external_gain_lineEdit.setObjectName("external_gain_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.external_gain_lineEdit)
        self.dev_mac_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_mac_lineEdit.setObjectName("dev_mac_lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dev_mac_lineEdit)
        self.dpowstart = QtWidgets.QPushButton(self.centralwidget)
        self.dpowstart.setGeometry(QtCore.QRect(494, 400, 141, 23))
        self.dpowstart.setObjectName("dpowstart")
        MainWindow.setCentralWidget(self.centralwidget)

        self.pdow.setText("整机功率校准")
        self.local_label.setText("本机IP")
        self.dev_ip_label.setText("设备IP")
        self.sa_ip_label.setText("仪器IP")
        self.mssh_port_label.setText("主控ssh端口")
        self.mssh_user_label.setText("主控登陆用户")
        self.mssh_password_label.setText("主控登陆密码")
        self.mssh_password_label_2.setText("主控登陆密码2")
        self.external_gain_label.setText("外部衰减")
        self.dev_mac_lable.setText("设备mac")
        self.dpowstart.setText("start")

        self.dpowstart.clicked.connect(lambda : execute.dpowrun(self,MainWindow))



if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())