# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MX2080整机产测.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MX2080 = QtWidgets.QLabel(self.centralwidget)
        self.MX2080.setGeometry(QtCore.QRect(310, 20, 141, 16))
        self.MX2080.setObjectName("MX2080")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 271, 412))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.plat_name_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.plat_name_lable.setObjectName("plat_name_lable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.plat_name_lable)
        self.plat_name_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.plat_name_comboBox.setObjectName("plat_name_comboBox")
        self.plat_name_comboBox.addItem("")
        self.plat_name_comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plat_name_comboBox)
        self.dev_type_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_type_label.setObjectName("dev_type_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dev_type_label)
        self.dev_type_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.dev_type_comboBox.setObjectName("dev_type_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dev_type_comboBox)
        self.oem_company_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.oem_company_lable.setObjectName("oem_company_lable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.oem_company_lable)
        self.oem_company_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.oem_company_comboBox.setObjectName("oem_company_comboBox")
        self.oem_company_comboBox.addItem("")
        self.oem_company_comboBox.addItem("")
        self.oem_company_comboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.oem_company_comboBox)
        self.local_ip_lable = QtWidgets.QLabel(self.formLayoutWidget)
        self.local_ip_lable.setObjectName("local_ip_lable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.local_ip_lable)
        self.local_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.local_ip_lineEdit.setObjectName("local_ip_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.local_ip_lineEdit)
        self.dev_ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_ip_label.setObjectName("dev_ip_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.dev_ip_label)
        self.dev_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_ip_lineEdit.setObjectName("dev_ip_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dev_ip_lineEdit)
        self.mssh_port_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_port_label.setObjectName("mssh_port_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mssh_port_label)
        self.mssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_port_lineEdit.setObjectName("mssh_port_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mssh_port_lineEdit)
        self.mssh_user_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_user_label.setObjectName("mssh_user_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mssh_user_label)
        self.mssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_user_lineEdit.setObjectName("mssh_user_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mssh_user_lineEdit)
        self.mssh_password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label.setObjectName("mssh_password_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label)
        self.mssh_pass_word_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_pass_word_lineEdit.setObjectName("mssh_pass_word_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mssh_pass_word_lineEdit)
        self.mssh_password_label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label_2.setObjectName("mssh_password_label_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label_2)
        self.mssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit.setObjectName("mssh_password_lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit)
        self.mcb_version_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mcb_version_label.setObjectName("mcb_version_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.mcb_version_label)
        self.mcb_version_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mcb_version_lineEdit.setObjectName("mcb_version_lineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.mcb_version_lineEdit)
        self.upper_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.upper_limit_label.setObjectName("upper_limit_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.upper_limit_label)
        self.lower_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.lower_limit_label.setObjectName("lower_limit_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lower_limit_label)
        self.rssi_lower_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.rssi_lower_limit_label.setObjectName("rssi_lower_limit_label")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.rssi_lower_limit_label)
        self.rssi_lower_limit_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rssi_lower_limit_lineEdit.setObjectName("rssi_lower_limit_lineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.rssi_lower_limit_lineEdit)
        self.rssi_upper_limit_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.rssi_upper_limit_label.setObjectName("rssi_upper_limit_label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.rssi_upper_limit_label)
        self.rssi_upper_limit_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rssi_upper_limit_lineEdit.setObjectName("rssi_upper_limit_lineEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.rssi_upper_limit_lineEdit)
        self.power_warn_time_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.power_warn_time_label.setObjectName("power_warn_time_label")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.power_warn_time_label)
        self.power_warn_time_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.power_warn_time_spinBox.setMaximum(3600)
        self.power_warn_time_spinBox.setObjectName("power_warn_time_spinBox")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.power_warn_time_spinBox)
        self.log_level_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.log_level_label.setObjectName("log_level_label")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.log_level_label)
        self.log_level_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.log_level_spinBox.setMaximum(7)
        self.log_level_spinBox.setObjectName("log_level_spinBox")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.log_level_spinBox)
        self.upper_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.upper_limit_spinBox.setMinimum(1)
        self.upper_limit_spinBox.setMaximum(100)
        self.upper_limit_spinBox.setObjectName("upper_limit_spinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.upper_limit_spinBox)
        self.lower_limit_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.lower_limit_spinBox.setObjectName("lower_limit_spinBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lower_limit_spinBox)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(340, 70, 261, 318))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nchp_lte_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_lte_version_label.setObjectName("nchp_lte_version_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nchp_lte_version_label)
        self.nchp_lte_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.nchp_lte_version_comboBox.setObjectName("nchp_lte_version_comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nchp_lte_version_comboBox)
        self.nchp_gsm_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nchp_gsm_version_label.setObjectName("nchp_gsm_version_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nchp_gsm_version_label)
        self.nchp_gsm_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.nchp_gsm_version_comboBox.setObjectName("nchp_gsm_version_comboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nchp_gsm_version_comboBox)
        self.count_lower_limit_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.count_lower_limit_label.setObjectName("count_lower_limit_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.count_lower_limit_label)
        self.count_lower_limitt_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.count_lower_limitt_spinBox.setObjectName("count_lower_limitt_spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.count_lower_limitt_spinBox)
        self.cpu_num_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.cpu_num_label.setObjectName("cpu_num_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cpu_num_label)
        self.cpu_num_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.cpu_num_spinBox.setMaximum(98)
        self.cpu_num_spinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.cpu_num_spinBox.setObjectName("cpu_num_spinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cpu_num_spinBox)
        self.led_pins_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.led_pins_label.setObjectName("led_pins_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.led_pins_label)
        self.led_pins_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.led_pins_lineEdit.setObjectName("led_pins_lineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.led_pins_lineEdit)
        self.rtc_in_cpu_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rtc_in_cpu_label.setObjectName("rtc_in_cpu_label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.rtc_in_cpu_label)
        self.rtc_in_cpu_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.rtc_in_cpu_spinBox.setObjectName("rtc_in_cpu_spinBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rtc_in_cpu_spinBox)
        self.wifi_in_cpu_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.wifi_in_cpu_label.setObjectName("wifi_in_cpu_label")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.wifi_in_cpu_label)
        self.wifi_in_cpu_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.wifi_in_cpu_spinBox.setObjectName("wifi_in_cpu_spinBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.wifi_in_cpu_spinBox)
        self.cell_mode_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.cell_mode_label.setObjectName("cell_mode_label")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.cell_mode_label)
        self.cell_mode_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.cell_mode_lineEdit.setObjectName("cell_mode_lineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cell_mode_lineEdit)
        self.TDD_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.TDD_version_label.setObjectName("TDD_version_label")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.TDD_version_label)
        self.TDD_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.TDD_version_comboBox.setObjectName("TDD_version_comboBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.TDD_version_comboBox)
        self.FDD_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.FDD_version_label.setObjectName("FDD_version_label")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.FDD_version_label)
        self.FDD_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.FDD_version_comboBox.setObjectName("FDD_version_comboBox")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.FDD_version_comboBox)
        self.GSM_version_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.GSM_version_label.setObjectName("GSM_version_label")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.GSM_version_label)
        self.GSM_version_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.GSM_version_comboBox.setObjectName("GSM_version_comboBox")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.GSM_version_comboBox)
        self.loadltever = QtWidgets.QPushButton(self.centralwidget)
        self.loadltever.setGeometry(QtCore.QRect(610, 70, 31, 23))
        self.loadltever.setObjectName("loadltever")
        self.loadgsmver = QtWidgets.QPushButton(self.centralwidget)
        self.loadgsmver.setGeometry(QtCore.QRect(610, 100, 31, 23))
        self.loadgsmver.setObjectName("loadgsmver")
        self.mx2080_start = QtWidgets.QPushButton(self.centralwidget)
        self.mx2080_start.setGeometry(QtCore.QRect(510, 480, 121, 23))
        self.mx2080_start.setObjectName("mx2080_start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MX2080.setText(_translate("MainWindow", "MX2080整机产测"))
        self.plat_name_lable.setText(_translate("MainWindow", "设备型号"))
        self.plat_name_comboBox.setItemText(0, _translate("MainWindow", "MX2080-G2L4"))
        self.plat_name_comboBox.setItemText(1, _translate("MainWindow", "MX2080-L4"))
        self.dev_type_label.setText(_translate("MainWindow", "设备类型"))
        self.oem_company_lable.setText(_translate("MainWindow", "oem"))
        self.oem_company_comboBox.setItemText(0, _translate("MainWindow", "fiberhome"))
        self.oem_company_comboBox.setItemText(1, _translate("MainWindow", "other"))
        self.oem_company_comboBox.setItemText(2, _translate("MainWindow", "unset"))
        self.local_ip_lable.setText(_translate("MainWindow", "本机IP"))
        self.dev_ip_label.setText(_translate("MainWindow", "主控IP"))
        self.mssh_port_label.setText(_translate("MainWindow", "主控ssh端口"))
        self.mssh_user_label.setText(_translate("MainWindow", "主控ssh用户"))
        self.mssh_password_label.setText(_translate("MainWindow", "主控ssh一级密码"))
        self.mssh_password_label_2.setText(_translate("MainWindow", "主控ssh二级密码"))
        self.mcb_version_label.setText(_translate("MainWindow", "主控版本"))
        self.upper_limit_label.setText(_translate("MainWindow", "温度上限"))
        self.lower_limit_label.setText(_translate("MainWindow", "温度下限"))
        self.rssi_lower_limit_label.setText(_translate("MainWindow", "WiFi信号强度上限"))
        self.rssi_upper_limit_label.setText(_translate("MainWindow", "WiFi信号强度下限"))
        self.power_warn_time_label.setText(_translate("MainWindow", "掉电告警等待时间"))
        self.log_level_label.setText(_translate("MainWindow", "日志打印级别"))
        self.nchp_lte_version_label.setText(_translate("MainWindow", "lte对应版本"))
        self.nchp_gsm_version_label.setText(_translate("MainWindow", "gsm对应版本"))
        self.count_lower_limit_label.setText(_translate("MainWindow", "上号数量下限"))
        self.cpu_num_label.setText(_translate("MainWindow", "cpu个数"))
        self.led_pins_label.setText(_translate("MainWindow", "led引脚"))
        self.rtc_in_cpu_label.setText(_translate("MainWindow", "rtc_in_cpu"))
        self.wifi_in_cpu_label.setText(_translate("MainWindow", "wifi_in_cpu"))
        self.cell_mode_label.setText(_translate("MainWindow", "cell_mode"))
        self.TDD_version_label.setText(_translate("MainWindow", "TDD版本"))
        self.FDD_version_label.setText(_translate("MainWindow", "FDD版本"))
        self.GSM_version_label.setText(_translate("MainWindow", "GSM版本"))
        self.loadltever.setText(_translate("MainWindow", "上传"))
        self.loadgsmver.setText(_translate("MainWindow", "上传"))
        self.mx2080_start.setText(_translate("MainWindow", "start"))
