# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '整机功率校准.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pdow = QtWidgets.QLabel(self.centralwidget)
        self.pdow.setGeometry(QtCore.QRect(280, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pdow.setFont(font)
        self.pdow.setObjectName("pdow")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 60, 241, 230))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.local_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.local_label.setObjectName("local_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.local_label)
        self.local_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.local_ip_lineEdit.setObjectName("local_ip_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.local_ip_lineEdit)
        self.dev_ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.dev_ip_label.setObjectName("dev_ip_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dev_ip_label)
        self.dev_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.dev_ip_lineEdit.setObjectName("dev_ip_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dev_ip_lineEdit)
        self.sa_ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.sa_ip_label.setObjectName("sa_ip_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sa_ip_label)
        self.sa_ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sa_ip_lineEdit.setObjectName("sa_ip_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sa_ip_lineEdit)
        self.mssh_port_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_port_label.setObjectName("mssh_port_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mssh_port_label)
        self.mssh_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_port_lineEdit.setObjectName("mssh_port_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mssh_port_lineEdit)
        self.mssh_user_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_user_label.setObjectName("mssh_user_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mssh_user_label)
        self.mssh_password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label.setObjectName("mssh_password_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label)
        self.mssh_password_label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.mssh_password_label_2.setObjectName("mssh_password_label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mssh_password_label_2)
        self.external_gain_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.external_gain_label.setObjectName("external_gain_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.external_gain_label)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.mssh_user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_user_lineEdit.setObjectName("mssh_user_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mssh_user_lineEdit)
        self.mssh_password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit.setObjectName("mssh_password_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit)
        self.mssh_password_lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mssh_password_lineEdit_2.setObjectName("mssh_password_lineEdit_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mssh_password_lineEdit_2)
        self.external_gain_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.external_gain_lineEdit.setObjectName("external_gain_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.external_gain_lineEdit)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.dpowstart = QtWidgets.QPushButton(self.centralwidget)
        self.dpowstart.setGeometry(QtCore.QRect(494, 400, 141, 23))
        self.dpowstart.setObjectName("dpowstart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.dpowstart.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pdow.setText(_translate("MainWindow", "整机功率校准"))
        self.local_label.setText(_translate("MainWindow", "本机IP"))
        self.dev_ip_label.setText(_translate("MainWindow", "设备IP"))
        self.sa_ip_label.setText(_translate("MainWindow", "仪器IP"))
        self.mssh_port_label.setText(_translate("MainWindow", "主控ssh端口"))
        self.mssh_user_label.setText(_translate("MainWindow", "主控登陆用户"))
        self.mssh_password_label.setText(_translate("MainWindow", "主控登陆密码"))
        self.mssh_password_label_2.setText(_translate("MainWindow", "主控登陆密码2"))
        self.external_gain_label.setText(_translate("MainWindow", "外部衰减"))
        self.label_10.setText(_translate("MainWindow", "载波频率"))
        self.dpowstart.setText(_translate("MainWindow", "start"))
